### ISSUE TITLE
CSS is not minified

### ISSUE THREAD

**Issue by gforcada** [datakurre/plonetheme-webpack-plugin#15]
With the ``production`` configuration, I would have expected that the assets are minified.

It is for JS, but seems that CSS is left alone unminified.

On this issue https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/434 there are a few pointers (webpackv2 related) on how to achieve it.

Was it an conscious choice not to minify it?

**Comment by datakurre** [comment]
It was not intentional. Probably because I had to keep very old css-loader for build performance.

**Comment by gforcada** [comment]
:tada: :bowing_man: thanks a lot!!!
