### ISSUE TITLE
Change log?

### ISSUE THREAD

**Issue by gforcada** [datakurre/plonetheme-webpack-plugin#3]
Hi,

it would be nice to keep a changelog, as users that still are on webpack1 know up to which version they can update until they need to move to webpack 2 (or 3) 😄 

Thanks for this plugin!!!

**Comment by datakurre** [comment]
Thanks. It will help me on that to know that someone else is using this.

Also my error that I did not release the 1.x version as 1.0 and went 2.x for webpack >= 2.0
