### ISSUE TITLE
Update to webpack 4?

### ISSUE THREAD

**Issue by gforcada** [datakurre/plonetheme-webpack-plugin#4]
Hi!

Are there any plans for updating this plugin to webpack 4? I guess that at least pull requests would be welcome? :smile:

**Comment by datakurre** [comment]
@gforcada Yes, pulls are welcome :) There were some major changes in plugin architecture in Webpack 3 that I haven’t been able to check.

Also check the state of css-loader. It has been pinned to very old version (probably not compatible with newer webpack), because the performance was terrible (like every update took a minute) with newer ones.

**Comment by datakurre** [comment]
I’d like to add that we are still using this for all our Plone 5 sites, but we haven’t created new themes for a while and that’s why have not been able update this.

Something I’ve been wanting to look into is to get this work better with Plone requirejs. We did get requirejs to work in webpack built theme already, but did not yet adapt that to Plone requirejs config.

**Comment by datakurre** [comment]
Would there be significant benefits for bunding / splitting / optimizations from the new version? That might help me to get time for this.

And that css-loader issue should be resolved :/ I haven’t checked that for a while.

**Comment by gforcada** [comment]
We have been fine tuning our digital.freitag.de assets (a django app) and I must say that yes, while trying to port that over to freitag.de (plone) I do miss quite a lot some of the plugins/techniques I used there. Specially regarding the bundle splitting, I try to lazy load as much as possible to increase performance (i rely on lighthouse for performance guidelines).

It would be great if you could have time to update this plugin to webpack4.

On a related note, maybe, to be honest I haven't had the time to look into it carefully enough, this PLIP https://github.com/plone/Products.CMFPlone/issues/1653 might be what we are all looking for, proper NPM packages that we can use without even having to have this plugin around and a plone instance running.

**Comment by datakurre** [comment]
Meanwhile, if you want to try this without the plugin, you can try what I did before the plugin https://github.com/datakurre/plonetheme.webpack

**Comment by gforcada** [comment]
That one says it is deprecated pointing to https://github.com/ebrehault/plonetheme.webpacktemplate which is alredy using this plugin :sweat_smile:

**Comment by datakurre** [comment]
Yes, it is deprecated, because I stopped updating it once I made the plugin. But before the plugin, I tried to use plain Webpack and just get all the javascripts and styles from their original sources. That was not fun back then, but might help to estimate that PLIP.

**Comment by datakurre** [comment]
Webpack 4 version is now at master. Release imminent. I'm working on updating plonetheme.webpacktemplate.
