### ISSUE TITLE
commons chunks does not work?

### ISSUE THREAD

**Issue by gforcada** [datakurre/plonetheme-webpack-plugin#6]
When using this plugin together with ``BundleAnalyzerPlugin`` and the usual (coming from the plonetheme.webpacktemplate) two entry points for anonymous and logged-in, one sees that it generates:

- default.js (~100kb)
- logged-in.js (300 **bytes**)
- commons.js (**1.5 kb**)
- xxx1.js (500kb)
- xxx2.js (150kb)

The commons, which should be rather big, as I assume it is meant to hold all the common parts between the two entry points is almost non-existing, while the other bundles are quite big.

Inspecting the bundles with BundleAnalyzerPlugin one can see that jquery, select2, backbone and some mockup/patternslib patterns are duplicated.

Who is to blame here? :thinking:  webpack2? this plugin? mockup itself? :thinking:

The total file sizes could be easily reduced at least 20-40% by deduplicating all these modules.

I stared at the code quite a few times but was clueless on how to move forward :sweat:

**Comment by datakurre** [comment]
Thanks for noticing that. Could it be order of the plugins? commons is created by CommonsChunkPlugin

https://github.com/datakurre/plonetheme-webpack-plugin/blob/master/index.js#L616

If moving that does not have any effect, then I should really find time to upgrade for Webpack 4 so that we had the latest versions before digging too much into details.

**Comment by datakurre** [comment]
And maybe we could try some “dedupeplugin”, but those might be already default in newer versions.

Once this works, it is also possible to add lazy loaded chunks. I have only used it for some large add-on libraries (like mathjax), but maybe we could figure out best practices for that in Plone core. Eg. TinyMCE should be lazy loaded.

**Comment by datakurre** [comment]
This works properly with Webpack 4 now so I'm closing this.

Although, the new plonetheme.webpacktemplate will default to only have a single entrypoint where all required splits are created with webpack dynamic imports. So, the plugin defaults to use the default webpack 4 splitChunk-configuration, but that can of course be overridden in webpack.config.js.

**Comment by datakurre** [comment]
@gforcada FYI. With Webpack 4 version there is no default configuration for its splitChunks setting so you can add whatever cachegroups you need :)
